# Generated by Django 6.0.1 on 2026-01-09 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='active_manager',
            field=models.ForeignKey(blank=True, help_text="The user currently responsible for this canteen's orders.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_canteens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canteen',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily disable this canteen.'),
        ),
        migrations.AddField(
            model_name='order',
            name='request_id',
            field=models.UUIDField(blank=True, help_text='Idempotency key to prevent duplicate orders', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CanteenManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.canteen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
