# Generated by Django 6.0.1 on 2026-01-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_canteenmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_id',
            field=models.UUIDField(blank=True, help_text='Idempotency key to prevent duplicate orders', null=True, unique=True),
        ),
    ]
