# Generated by Django 6.0.1 on 2026-01-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='active_manager',
            field=models.ForeignKey(blank=True, help_text="The user currently responsible for this canteen's orders.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_canteens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canteen',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily disable this canteen.'),
        ),
    ]
